# We do not need sudo, but want to use xenial.
sudo: false
dist: xenial

language: node_js

# Run tests against the latest version of node, and the latest LTS.
node_js:
  - 8
  - 10
  - 12
  - node
  - lts/*
